variables:
  sonarprojectKey: 'learning-spring'
  jdkversion: '1.11'
  artifactname: 'BankCustomerApp'
  azuresubscription: '<your susbscription ID>'
  rgname: '<resource group>'
  webapp: 'BankCustomerApp'
  azureResourceManagerConnection: '<arm connection name>'
  subscriptionId: '<your subscription id>'
  resourceGroupName: '<resource group name>'




 


